### ISSUE TITLE
No desktop file

### ISSUE THREAD

**Issue by null-von-sushi** [jgressmann/harbour-vodman#12]
After installation I got no icon in the app menu

**Comment by null-von-sushi** [comment]
Tab-completion in the terminal also lists
vodman-youtube-dl,  vodman-service and vodman-cli. Nothing that seems Graphical, despite the open repos page having screenshots of a GUI app

**Comment by null-von-sushi** [comment]
manually installing v. 1.1.4 from the website fixes this

**Comment by jgressmann** [comment]
Not sure what happened with your installation but it seems you were running a rather old  version. 
Once upon a time version (1.0.10) Vodman was using multiple rpms, now there is only the app itself. 

Have you tried to refresh the repository sources on your device? The current version is 1.2.0

**Comment by jgressmann** [comment]
The last version of libvodman, libvodman-devel, vodman-service etc are still hosted on Openrepos. You should remove everything but harbour-vodman and upgrade to the latest version of the app.

**Comment by null-von-sushi** [comment]
honestly I installed SFOS from scratch like a few days ago . I had some problems with the new update and storeman, but I think its fixed now. as for vodman, after installing the previous version I got my desktop file back, and it's still there after updating .

So I guess it's fine for now ? I'll close the issue since I don't have anything useful , but should  it happen again I'll reopen the issue.
