### ISSUE TITLE
Direct file download doesn't work

### ISSUE THREAD

**Issue by zwieberl** [jgressmann/harbour-vodman#2]
Hi, 
downloading a URL that is a direct link to a video-file does not work (URL ending with .mp4, e.g.: http://techslides.com/demos/samples/sample.mp4).
Would be great if this was supported.

Background: I'm the author of the sailfish app "Fishtheke", which lets you search for VODs and gives you direct URLs to videos. People have requested to be able to easily download those videos.
It would be great if VODman could handle this. Otherwise I would need to reimplement most of your app in mine.

**Comment by jgressmann** [comment]
Hi there,

looks like it fails because there is no audio component in json meta data
for the video. Should be easy enough to support your use case.

Cheers
J

**Comment by jgressmann** [comment]
Done, 94fa7aafe8d897e9b8f7990f59af2539b5d472c1

Cheers,
J
