### ISSUE TITLE
[feature request] Add possibility to send URL from other apps

### ISSUE THREAD

**Issue by zwieberl** [jgressmann/harbour-vodman#3]
Fishtheke already can send its URLs to various apps. It would be nice, if I could send it to vodman as well. Either via commandline-arguments or a simple dbus-interface.
One can of course copy it to clipboard and switch manually to vodman, to paste it. A simple "Send to vodman" would be more comfortable though. 

Would this be possible, by any chance?
Jopii has a simple dbus-interface like this and could be used as a template.

**Comment by jgressmann** [comment]
Done, 1aae45bef06b9949d7c29e220df81e537db6a247

For an example, see commit message.
